insert INTO workouts (workout_name, workout_sets, workout_reps, workout_category,workout_order, workout_level)
VALUES ('Lunges', 3, 8, Legs, 1, 'Beginner')
insert INTO workouts (workout_name, workout_sets, workout_reps, workout_category,workout_order, workout_level)
VALUES ('Body Weight Squats', 3, 12, Legs, 2, 'Beginner')
insert INTO workouts (workout_name, workout_sets, workout_reps, workout_category,workout_order, workout_level)
VALUES ('Box Jumps', 3, 8, Legs, 3, 'Beginner')
insert INTO workouts (workout_name, workout_sets, workout_reps, workout_category,workout_order, workout_level)
VALUES ('Side Lunges', 3, 8, Legs, 1, 'Beginner')

insert INTO workouts (workout_name, workout_sets, workout_reps, workout_category,workout_order, workout_level)
VALUES ('Lunges', 3, 12, Legs, 1, 'Intermediate')
insert INTO workouts (workout_name, workout_sets, workout_reps, workout_category,workout_order, workout_level)
VALUES ('Squat', 3, 12, Legs, 2, 'Intermediate')
insert INTO workouts (workout_name, workout_sets, workout_reps, workout_category,workout_order, workout_level)
VALUES ('Box Jumps', 3, 12, Legs, 3, 'Intermediate')
insert INTO workouts (workout_name, workout_sets, workout_reps, workout_category,workout_order, workout_level)
VALUES ('Side Lunges', 3, 12, Legs, 1, 'Intermediate')

insert INTO workouts (workout_name, workout_sets, workout_reps, workout_category,workout_order, workout_level)
VALUES ('Dumbell Lunges', 3, 12, Legs, 1, 'Advanced')
insert INTO workouts (workout_name, workout_sets, workout_reps, workout_category,workout_order, workout_level)
VALUES ('Split-Squat', 3, 12, Legs, 2, 'Advanced')
insert INTO workouts (workout_name, workout_sets, workout_reps, workout_category,workout_order, workout_level)
VALUES ('Box Jumps', 3, 12, Legs, 4, 'Advanced')
insert INTO workouts (workout_name, workout_sets, workout_reps, workout_category,workout_order, workout_level)
VALUES ('Dumbell Side Lunges', 3, 12, Legs, 1, 'Advanced')
insert INTO workouts (workout_name, workout_sets, workout_reps, workout_category,workout_order, workout_level)
VALUES ('Single-Leg Romainian Deadlift', 3, 6, Legs, 3, 'Advanced')
